// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4NTV4x_dazFK0v6njMND3CxBfVqX692Y',
    appId: '1:655912534038:android:075d0ea772b5ece34eb537',
    messagingSenderId: '655912534038',
    projectId: 'dayflow-e87c0',
    storageBucket: 'dayflow-e87c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxOIDGeV-iB0b4KxSnL6mz6oRKthzM-mE',
    appId: '1:655912534038:ios:ef3517d946cb0b1b4eb537',
    messagingSenderId: '655912534038',
    projectId: 'dayflow-e87c0',
    storageBucket: 'dayflow-e87c0.firebasestorage.app',
    iosBundleId: 'com.example.dayflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADvPMRJnTwTOtYsceMJ8U_Pj_yXD51aWc',
    appId: '1:655912534038:web:14599e0bb3be61c24eb537',
    messagingSenderId: '655912534038',
    projectId: 'dayflow-e87c0',
    authDomain: 'dayflow-e87c0.firebaseapp.com',
    storageBucket: 'dayflow-e87c0.firebasestorage.app',
    measurementId: 'G-QC6E20DF3P',
  );
}
